### ISSUE TITLE
The world goes deeper now; perhaps revisit depth check?

### ISSUE THREAD

**Issue by dreamlibrarian** [daedalus4096/PrimalMagick#102]
https://github.com/daedalus4096/PrimalMagick/blob/5e5f7ea55f3383c071ca0bc5523294c5b41b8adc/src/main/java/com/verdantartifice/primalmagick/common/events/PlayerEvents.java#L260

**Comment by daedalus4096** [comment]
As of v3.0.1, completing Source: The Earth will require travelling to y: -16, and completing Source: The Sky will require travelling to y: 128.
