### ISSUE TITLE
Spell crash

### ISSUE THREAD

**Issue by Serifina** [daedalus4096/PrimalMagick#112]
Upon casting a spell, the server crashed. Because the spell tried to waterlog stone?

https://pastebin.com/Zdfpb2kP Crashlog is here

Spell was Projectile/Conjure Stone, applied to a gold-capped heartwood apprentice wand, and the spell was fired into a river.

Minecraft 1.18.2
Forge 40.1.54
Primal Magic 2.1.2

**Comment by daedalus4096** [comment]
This bug should be fixed in the upcoming release v3.0.1.  Please file a new ticket if you encounter it again.  Thanks for the report!
