### ISSUE TITLE
Earthshatter Hammer Gupe-Glitch

### ISSUE THREAD

**Issue by Nachtflame** [daedalus4096/PrimalMagick#113]
Primal Magick: 2.1.2
Forge: 40.1.52

Description:
Crafting two partially damaged *Earthshatter Hammers* together to repair them, instead results in removal of a single durability from the two input hammers (leaving them in the grid) while generating a 3rd higher durability hammer.

Expected Behavior:
Input hammers would be removed.

**Comment by daedalus4096** [comment]
Thank you for the report!  This is a known issue in that version, with a fix slated to be included in the upcoming release v3.0.1.  Specifically, Earthshatter Hammers will no longer be able to be combined in this fashion.  Please file a new ticket if you still encounter issues with this item once that release is out.
