### ISSUE TITLE
(Compatibility) Arcane Workbench and Ritual Altar recipes are picked up by Create devices

### ISSUE THREAD

**Issue by TheRealWormbo** [daedalus4096/PrimalMagick#117]
From what I can tell, all Ritual Altar recipes are picked up as "automated shapeless crafting" for basin plus mechanical mixer, without requiring nay of the props or mana. For the Arcane Workbench, only shapeless and "packing" recipes (shaped recipe with 2x2 or 3x3 of a single input item) are picked up for the mixer and mechanical press, respectively.
Other shaped Arcane Workbench recipes are correctly ignored by Create. The only recipe Create also picks up for its Mechanical Crafter are single-item shapeless "unpacking" recipes for the Arcane Workbench, but that seems to be JEI-only. The mechanical crafter doesn't actually accept the input item for those.

I *assume* that this is mostly Create's fault (and I reported it over there as well: Creators-of-Create/Create/issues/3591), but I'm leaving this issue here mainly for reference and in case you might be able to provide any insights for a potential fix.

**Comment by daedalus4096** [comment]
While this is definitely a bug, I'm pretty sure that it's on Create's end.  Primal Magick uses a number of custom recipe types, and it looks like Create is ingesting them when it shouldn't be.  Thank you for reporting this bug in both places.  I'm not aware of anything I can do on my end to fix it, but I'm happy to work with the authors of Create if there are compatibility steps I can take that they can share, or I can share information with them on PM's custom recipe types so they can be appropriately blacklisted.  Leaving this issue open for reference until a solution can be found.

**Comment by daedalus4096** [comment]
This issue should be fixed in a future update.  On my end, the changes required will be in v4.0.2 of Primal Magick, the next planned release.  A change has also been made on Create's end, but I can't speak to when that will make it live.  Thank you for the report!
