### ISSUE TITLE
Server crash when killing entities from other mods with Essence Thief enchantment.

### ISSUE THREAD

**Issue by DaForq** [daedalus4096/PrimalMagick#121]
I was playing in my 1.18.2 modded server, with a sword with several enchantments on it, when the server crashed and brought me to the multiplayer screen, after killing a mob from the mod Evilcraft. After some more testing, the same happened with entities from the mods Ars Nouveau and Twilight Forest, all three with a Ticking entity error, reading "java.lang.NullPointerException: Cannot invoke "com.verdantartifice.primalmagick.common.sources.SourceList.isEmpty()" because "affinities" is null", which I believe is caused by the Essence Thief enchantment, since the crash won't happen if I use the same swords with the same enchantments except for that one.

**Comment by daedalus4096** [comment]
This issue should be fixed in the next release, currently planned as v3.2.0.  Thank you for the bug report!
