### ISSUE TITLE
Server Crash - java.lang.NoClassDefFoundError: net/minecraft/client/resources/model/ModelResourceLocation

### ISSUE THREAD

**Issue by rckymtnrfc** [daedalus4096/PrimalMagick#127]
Forge 43.1.16
Primal Magick 3.2.0

[latest.log](https://pastebin.com/0nk9FR0n)  I had to cut it down as it was  too large for pastebin but I think it covers what you'll need to know.  FYI, the client starts just fine, it's only the server this happens.

Thanks!

**Comment by waddon1** [comment]
I believe I'm also having this crash

https://pastebin.com/wkj8RDHd

**Comment by daedalus4096** [comment]
Thank you for the report, and the detailed logs.  This issue should be fixed in the next release, v3.2.1.
