### ISSUE TITLE
[1.19.2]Small freezes trying to view affinities

### ISSUE THREAD

**Issue by nin8995** [daedalus4096/PrimalMagick#133]
I installed many mods and every time I use shift key over items, to move stacks of items or to get information, it usually freezes a little bit with the tooltip "Affinities: Unknown".
I expected that when an item can have internal affinity values, it doesn't freeze, otherwise it freezes, so I played without Primal Magick and it didn't freeze.
I really need any performance improvements or config not to show affinities when pressing shift key.

This phenomenon can be ascertained with almost all the modpacks including Primal Magick.
For instance I tested [Chunk Block by Joshernoob](https://www.curseforge.com/minecraft/modpacks/chunk-block), because it was the first modpack which has latest version of this mod searching [dependents](https://www.curseforge.com/minecraft/mc-mods/primal-magick/relations/dependents), and it froze. Scrolling JEI pages pressing shift key is easy to feel small freezes.

**Comment by zjdtmkhzt** [comment]
I am experiencing similar issues, it is most severe with items or blocks that contain things like planks, sticks, glass (?).
Many blocks that contain planks in their recipes, like vanilla job stations, seem to freeze once per startup when I hover over them while carrying an arcanometer.

In addition to that, some blocks or items, like items containing Archwood from Ars Nouveau or Raw Ore from the AllTheOres mod seem to never stop this freezing, hovering over them in the inventory while holding shift or hovering over them while carrying an Arcanometer seems to drop fps extremely low until you stop hovering over them, unlike plank items which just seem to take a long time to calculate or something.

I also tried with just Ars Nouveau and dependencies, and hovering over blocks like archwood planks with an arcanometer still seems to cut my fps in half, though the effect is less severe than in my big modpack.

Another thing I observed is that in the Allomancy mod, the freeze happens with (for example) Cadmium and Bendalloy flakes, but it does not occur with Duralumin flakes, which contain Copper flakes in their recipe and therefore have a value of 1 Earth.
So perhaps this has something to do with an item or block not getting any elements from their recipes and therefore somehow not terminating?

**Comment by Milii20** [comment]
Hello!, just logged in to say this also happens to me in 1.18.2's version (it's a gigantic personal modpack, about 480 mods), and it's way worst when you shift over a storage crate from immersive engineering full of items.
Also some items seem to be ok, while others (specially armor, tools and swords) are way laggier.
Maybe as an emergency fix, could we get at least a way to remap the key associated to view affinities? (And please for 1.18.2 too?)
Thank you for your time!

**Comment by unilock** [comment]
Same problem here. Related issues: #98, #111

I guess the problem stems from the Affinity value generation logic iterating through *every single recipe* that produces a given item, followed by the same for *every single item* that's a part of each of those recipes, then the same for the recipes of *those* items... and so on and so forth.
At least, that's what I gathered from a quick skim of [AffinityManager.java](https://github.com/daedalus4096/PrimalMagick/blob/master/src/main/java/com/verdantartifice/primalmagick/common/affinities/AffinityManager.java).

Maybe limit the Affinity tooltip to just vanilla + Primal Magick items/recipes? At least by default?
(default registry: [AffinityProvider.java](https://github.com/daedalus4096/PrimalMagick/blob/master/src/main/java/com/verdantartifice/primalmagick/datagen/affinities/AffinityProvider.java))

**Comment by Grath** [comment]
Any possibility we could get a release now that this issue is possibly fixed by #140? I just made a modpack with Primal Magick in it and this is causing noticeable obnoxious freezes when shift-clicking items, which about half my playerbase are already actively complaining about (and we only started playing the pack yesterday.)

**Comment by unilock** [comment]
@Grath I ran the "build" action manually; you can download the result here: https://github.com/unilock/PrimalMagick/actions/runs/5176550636
(for 1.19.2)

**Comment by unilock** [comment]
@Grath Try this. https://github.com/unilock/PrimalMagick/actions/runs/5181112906

**Comment by daedalus4096** [comment]
The next planned release of Primal Magick is the 1.20 compatibility release.  Mojang is releasing the patch tomorrow, after which I'm just dependent on Forge to release a recommended build of the mod loader.  I know this probably isn't the timeframe you were hoping for, and I'm sorry for that, but it shouldn't be too much longer now.

**Comment by Grath** [comment]
That won't help me at all, because it'll be many months before all the mods in my modpack are updated for 1.20 (if ever, several have shown no signs that they're being actively maintained on 1.19) so it sounds like I'm just stuck with options of "holes in the world from removing Primal Magick", "start a new world", or "deal with client freezing when I try to shift-click items".

**Comment by unilock** [comment]
@Grath New build: https://github.com/unilock/PrimalMagick/actions/runs/5194194710

I actually tested it this time, and both logical (client) and dedicated servers work. Though it might break if there's no "overworld" level - but hopefully that shouldn't ever be the case.

(It's supposed to say "Affinities: Unknown" by default, right...?)

**Comment by Grath** [comment]
@unilock Thank you for caring about this mod being playable in modpacks; it seems like it's running a bit better but still occasionally hits some lag calculating affinities (customizable tools can't be feasibly pre-calculated, for example.) I'll give it a shot running that build though.

**Comment by unilock** [comment]
Unfortunately, I'm not the one who programmed the affinity derivation system; just the one who got it running on dedicated servers. You'll want to poke @dreamlibrarian concerning anything else.

**Comment by daedalus4096** [comment]
This should be fixed in the upcoming 1.20.1 release.  Should you continue to encounter this sort of problem, please file a new ticket.  Thank you for your patience!
