### ISSUE TITLE
Tridents added by PrimalMagick do not break chorus fruit

### ISSUE THREAD

**Issue by kurushimi0** [daedalus4096/PrimalMagick#138]
When a vanilla Trident is thrown at a Chorus Fruit on the trees in The End, the impact will cause the Chorus Fruit to drop (and the Trident will return if enchanted with Loyalty). The tridents added by PrimalMagick, however, do not trigger the drops on impact.

**Comment by kurushimi0** [comment]
Just following up -- another mod's tridents have a similar problem, so it's quite possible that this is due to a conflict with some other mod or with modded tridents in general.

**Comment by daedalus4096** [comment]
This should be fixed in the upcoming 1.20.1 update for Primal Magick.  If you continue to encounter it, please file a new ticket.  Thank you for the report, and your patience.
