### ISSUE TITLE
Hopper interactions with Altars and Essence Cask

### ISSUE THREAD

**Issue by Carcnegorn** [daedalus4096/PrimalMagick#141]
In my version, hoppers aren't feeding materials into the Essence Cask.  This limits the automation of the Calcinator.

Also, the interaction with the Altars for rituals seems bugged.  Manually, I can only add one of each item to an altar, but the hoppers will keep feeding items up to a whole stack, and they all can be retrieved from the altar at once.  Visually, they just show as one of the item and the ritual consumes the whole stack, however.  This limits how much I can back-up and prepare my rituals.

**Comment by daedalus4096** [comment]
Both of these issues should be fixed in the next release, currently planned as v4.0.8, which should be available in the near future.  Please note, though, that Essence Casks currently only accept input from above, regardless of how they're oriented.  Thank you for the bug report and your patience.
