### ISSUE TITLE
[Request 1.19.2] Make view affinities key rebindable

### ISSUE THREAD

**Issue by faeldray** [daedalus4096/PrimalMagick#147]
I'm aware of issue #133 and that you introduced a fix in the 1.20.1 version and I completely understand not wanting to update for older versions of Minecraft. But if the fix won't be added to the 1.19.2, would it at least be possible to make the view affinities key rebindable?

I'm still on 1.19.2 because there are mods I want to play that haven't updated to 1.20 yet and due to wrist issues, I use the shift-click option from Inventory Essentials a lot to move stacks of items around quickly. The lag from affinities trying to show really slows that down and that means it affects my wrists more.

I'd be really grateful if you could add this feature, this mod is really cool and I'd like to play around with it more.

**Comment by daedalus4096** [comment]
As a rule, I don't maintain bug fixes for prior versions of the mod, save for really critical stuff like security issues.  That said, I will see what I can do to get your request implemented in 1.20.1 and forward.  I know that doesn't help you in the short term, and I apologize for that, but it may be of use if/when the other mods you play catch up.

**Comment by daedalus4096** [comment]
I've made the change that you've asked for in the upcoming v4.0.1 release of the mod for Minecraft 1.20.1.  I know that's not exactly what you were asking for, but it's the best I can do under my current long term support plan.  I'm going to close this issue as "not planned", since there won't be a fix for 1.19.2.
