### ISSUE TITLE
Arcane Recipe Book 

### ISSUE THREAD

**Issue by OblivionCultist** [daedalus4096/PrimalMagick#196]
I was rapidly opening, closing and reopening the Grimoire object looking at what I needed to pull out of chests for a recipe when a shutdown occurred. I believe the wand I was using disappeared at the same time but I didn't notice till later so it might not have been involved.

[crash-2023-09-26_08.41.00-client.txt](https://github.com/daedalus4096/PrimalMagick/files/12732554/crash-2023-09-26_08.41.00-client.txt)

**Comment by daedalus4096** [comment]
This crash should be fixed in the next release, currently planned as v4.0.6.  Thanks for the report!
