### ISSUE TITLE
Arrangement of runes in enchanting table decides which recipe happens

### ISSUE THREAD

**Issue by dreamlibrarian** [daedalus4096/PrimalMagick#203]
I was expecting that the row and column would decide which enchantments would apply for the enchanted table. 

Instead, I almost got somethig unexpected as my combo worked out to protection in one direction and _fire_ protection in another. 

It's possible this is somewhat intended per later rune tables, but it's definitely _surprising_ and confusing.

Screenshots below show the only difference is swapping the item and earth runes top to bottom.

The arrangement there is top to bottom item protect earth, left to right self protect infernal.

<img width="1470" alt="Screenshot 2023-10-02 at 8 57 09 PM" src="https://github.com/daedalus4096/PrimalMagick/assets/1129250/c76148ca-a383-4f2e-8e91-ad34e709c12b">
<img width="1470" alt="Screenshot 2023-10-02 at 8 57 27 PM" src="https://github.com/daedalus4096/PrimalMagick/assets/1129250/11203715-ef73-46fc-af7f-2e5b90402fdf">
<img width="1470" alt="Screenshot 2023-10-02 at 8 57 35 PM" src="https://github.com/daedalus4096/PrimalMagick/assets/1129250/d3838050-e2e6-4659-872e-7b1139b0a7ad">
<img width="1470" alt="Screenshot 2023-10-02 at 8 57 38 PM" src="https://github.com/daedalus4096/PrimalMagick/assets/1129250/6d28fe46-f6e9-4a18-bd74-e80f103695c8">

**Comment by daedalus4096** [comment]
I'm pretty sure I know what's happening here, the question is how best to fix it.  You've got the runes there for all three enchantments: Unbreaking, Protection, and Fire Protection.  It would give you all three, except that protection-type enchantments are mutually exclusive.  Right now it's breaking the conflict by applying the first valid combination it sees, but that clearly has issues.  I'm not sure if there's a technically feasible way that's smarter, though.  I'll investigate.  Thanks for the report.

**Comment by dreamlibrarian** [comment]
Yeah, only thing I could _vaguely_ hope for is probably no fun to implement
- search the horizontal line only, then the vertical line only, then the
whole blob and prefer earlier finds. clunky but less surprising.

**Comment by daedalus4096** [comment]
This should be fixed in the next release, currently planned as v4.0.6.  In the case of conflicting enchantments such as this, the enchantment with the higher minimum experience cost will now be preferred, breaking ties in a consistent manner.  The position of runes on the runescribing altar should now be irrelevant.  Please file a new ticket if you encounter any weirdness as a result of this change.  Thanks for the report!
