### ISSUE TITLE
Arcane Recipe Book Crash

### ISSUE THREAD

**Issue by OblivionCultist** [daedalus4096/PrimalMagick#208]
Crash while opening the Magick Workbench
[crash-2023-10-07_14.41.15-client.txt](https://github.com/daedalus4096/PrimalMagick/files/12839433/crash-2023-10-07_14.41.15-client.txt)

**Comment by daedalus4096** [comment]
This should be fixed in the next release, currently planned as v4.0.7.  Thanks for the report!
