### ISSUE TITLE
Mana Nexus mana displays incorrect in multiplayer

### ISSUE THREAD

**Issue by dreamlibrarian** [daedalus4096/PrimalMagick#209]
I could only repro this in multiplayer, and actual -state- of the block appears correct - it charges based on actual available mana capacity - but visually the individual mana values are wildly out of sync.

<img width="952" alt="Screenshot 2023-10-10 at 7 51 12 PM" src="https://github.com/daedalus4096/PrimalMagick/assets/1129250/d83439e0-e81a-4f44-8d6a-0bd050914349">
<img width="1064" alt="Screenshot 2023-10-10 at 7 53 06 PM" src="https://github.com/daedalus4096/PrimalMagick/assets/1129250/c243074e-af2a-4b21-84a1-6804b2b028aa">

**Comment by daedalus4096** [comment]
This should be fixed in the next release, currently planned as v4.0.7.  Thanks for the report!
