### ISSUE TITLE
Picking up Dream Journal crashes the client

### ISSUE THREAD

**Issue by Eslorex** [daedalus4096/PrimalMagick#219]
Picking up Dream Journal crashes the client till the mod is completely removed. It only happens when item picked up from the ground.

**Comment by Eslorex** [comment]
Removing mod from server and client fixed the issue.

**Comment by daedalus4096** [comment]
I'm sorry you encountered this error.  I'm unable to reproduce the problem on my end, though.  Do you have a crash report that you could attach to this ticket so that I can investigate further?  Thank you.

**Comment by Eos109** [comment]
okay so I have the problem too now, everything worked fine when in singleplayer, problem happened on a freshly started mp server... 
looking at the server log it says the following

09.11 17:39:27 [Server] Server thread/ERROR [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Could not initialize class com.verdantartifice.primalmagick.client.books.BookHelper
09.11 17:39:27 [Server] INFO 	Index: 11
09.11 17:39:27 [Server] INFO 	Listeners:
09.11 17:39:27 [Server] INFO 		0: HIGHEST
09.11 17:39:27 [Server] INFO 		1: net.minecraftforge.eventbus.EventBus$$Lambda$4211/0x00000008016d2000@223c77ef
09.11 17:39:27 [Server] INFO 		2: HIGH
09.11 17:39:27 [Server] INFO 		3: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
09.11 17:39:27 [Server] INFO 		4: NORMAL
09.11 17:39:27 [Server] INFO 		5: ASM: se.mickelus.tetra.effect.ItemEffectHandler@6cbdf8d onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
09.11 17:39:27 [Server] INFO 		6: ASM: class ironfurnaces.Config player(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
09.11 17:39:27 [Server] INFO 		7: ASM: class dev.ghen.thirst.content.thirst.PlayerThirstManager onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
09.11 17:39:27 [Server] INFO 		8: net.minecraftforge.eventbus.EventBus$$Lambda$4211/0x00000008016d2000@f0c7a9e
09.11 17:39:27 [Server] INFO 		9: ASM: class com.aetherteam.aether.event.listeners.EntityListener onRiderTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
09.11 17:39:27 [Server] INFO 		10: ASM: class com.aetherteam.aether.event.listeners.DimensionListener onPlayerTraveling(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
09.11 17:39:27 [Server] INFO 		11: ASM: class net.mcreator.createsweetsandtreets.procedures.SugarCookiePropertyValueProviderProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
09.11 17:39:27 [Server] INFO 		12: ASM: class net.mcreator.createsweetsandtreets.procedures.HoldTheRainbowProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
09.11 17:39:27 [Server] INFO 		13: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
09.11 17:39:27 [Server] INFO 		14: net.minecraftforge.eventbus.EventBus$$Lambda$4211/0x00000008016d2000@2e2514e
09.11 17:39:27 [Server] INFO 		15: ASM: class com.simibubi.create.content.equipment.bell.HauntedBellPulser hauntedBellCreatesPulse(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
09.11 17:39:27 [Server] INFO 		16: net.minecraftforge.eventbus.EventBus$$Lambda$4211/0x00000008016d2000@3d3db215
09.11 17:39:27 [Server] INFO 		17: ASM: mcjty.lib.setup.ModSetup$EventHandler@7804aaa5 onPlayerTickEvent(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
09.11 17:39:27 [Server] INFO 		18: ASM: mcjty.rftoolsutility.setup.ForgeEventHandlers@69f379dc onPlayerTickEvent(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
09.11 17:39:27 [Server] INFO 		19: LOW
09.11 17:39:27 [Server] INFO 		20: ASM: se.mickelus.tetra.items.forged.VibrationDebuffer@2f832cd8 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
09.11 17:39:27 [Server] INFO 		21: ASM: se.mickelus.tetra.items.modular.impl.toolbelt.booster.TickHandlerBooster@15e090a9 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
09.11 17:39:27 [Server] INFO 		22: LOWEST
09.11 17:39:27 [Server] INFO 		23: net.minecraftforge.eventbus.EventBus$$Lambda$4211/0x00000008016d2000@7c7f3952
09.11 17:39:27 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class com.verdantartifice.primalmagick.client.books.BookHelper
09.11 17:39:27 [Server] INFO 	at TRANSFORMER/primalmagick@4.0.7/com.verdantartifice.primalmagick.common.items.books.StaticBookItem.m_7626_(StaticBookItem.java:191)
09.11 17:39:27 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.m_41786_(ItemStack.java:580)
09.11 17:39:27 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.m_41611_(ItemStack.java:911)
09.11 17:39:27 [Server] INFO 	at TRANSFORMER/createsweetsandtreets@1.0.0/net.mcreator.createsweetsandtreets.procedures.SugarCookiePropertyValueProviderProcedure.execute(SugarCookiePropertyValueProviderProcedure.java:30)
09.11 17:39:27 [Server] INFO 	at TRANSFORMER/createsweetsandtreets@1.0.0/net.mcreator.createsweetsandtreets.procedures.SugarCookiePropertyValueProviderProcedure.onPlayerTick(SugarCookiePropertyValueProviderProcedure.java:19)
09.11 17:39:27 [Server] INFO 	at TRANSFORMER/createsweetsandtreets@1.0.0/net.mcreator.createsweetsandtreets.procedures.__SugarCookiePropertyValueProviderProcedure_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
09.11 17:39:27 [Server] INFO 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
09.11 17:39:27 [Server] INFO 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
09.11 17:39:27 [Server] INFO 	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
09.11 17:39:27 [Server] INFO 	at TRANSFORMER/forge@47.2.1/net.minecraftforge.event.ForgeEventFactory.onPlayerPostTick(ForgeEventFactory.java:920)
09.11 17:39:27 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_8119_(Player.java:285)
09.11 17:39:27 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467)
09.11 17:39:27 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262)
09.11 17:39:27 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.Connection.m_129483_(Connection.java:263)
09.11 17:39:27 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
09.11 17:39:27 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907)
09.11 17:39:27 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283)
09.11 17:39:27 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
09.11 17:39:27 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
09.11 17:39:27 [Server] INFO 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
09.11 17:39:27 [Server] INFO 	at java.base/java.lang.Thread.run(Thread.java:833)


followed by aproblem with sending packets based on this and repeating this, both repeat 4 times

**Comment by SidratG** [comment]
This issue seems to be happening on my dedicated server as well. Hosting on Debian, using Java OpenJDK 17, in a virtualized container for my friends. Whenever someone sleeps with the book it causes them to crash and then receive an internal server error upon the next login until their player data is removed manually. Anyone who is within the immediate area are also affected and crash.

Here is the error when they attempt to login:
```
[19:57:21] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Could not initialize class com.verdantartifice.primalmagick.client.books.BookHelper
        Index: 4
        Listeners:
                0: HIGH
                1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
                2: NORMAL
                3: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge onItemPickup(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
                4: ASM: stepsword.mahoutsukai.handlers.ServerHandler@4cf87e6a useItem(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
                5: ASM: wayoftime.bloodmagic.util.handler.event.WillHandler@cd815c onItemPickup(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
                6: net.minecraftforge.eventbus.EventBus$$Lambda$4230/0x00007fb9f0a93708@4638f01b
                7: ASM: Block{minecraft:air} onPickup(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
                8: net.minecraftforge.eventbus.EventBus$$Lambda$4230/0x00007fb9f0a93708@51c22512
                9: net.minecraftforge.eventbus.EventBus$$Lambda$4230/0x00007fb9f0a93708@30351a9b
                10: ASM: org.cyclops.cyclopscore.advancement.criterion.ModItemObtainedTrigger@27241068 onPickup(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
                11: ASM: com.lothrazar.cyclic.event.ItemEvents@68405efd onPlayerPickup(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
                12: ASM: mob_grinding_utils.events.ChickenFuseEvent@1b4b157d startChickenFuse(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
                13: LOWEST
                14: ASM: class com.hollingsworth.arsnouveau.common.event.EventHandler itemPickupEvent(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
java.lang.NoClassDefFoundError: Could not initialize class com.verdantartifice.primalmagick.client.books.BookHelper
        at TRANSFORMER/primalmagick@4.0.7/com.verdantartifice.primalmagick.common.items.books.StaticBookItem.m_7626_(StaticBookItem.java:191)
        at TRANSFORMER/mahoutsukai@1.20.1-v1.34.58/stepsword.mahoutsukai.effects.secret.GeasEffect.hasGeas(GeasEffect.java:143)
        at TRANSFORMER/mahoutsukai@1.20.1-v1.34.58/stepsword.mahoutsukai.effects.secret.GeasEffect.geasItem(GeasEffect.java:51)
        at TRANSFORMER/mahoutsukai@1.20.1-v1.34.58/stepsword.mahoutsukai.handlers.ServerHandler.useItem(ServerHandler.java:400)
        at TRANSFORMER/mahoutsukai@1.20.1-v1.34.58/stepsword.mahoutsukai.handlers.__ServerHandler_useItem_EntityItemPickupEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
        at TRANSFORMER/forge@47.2.4/net.minecraftforge.event.ForgeEventFactory.onItemPickup(ForgeEventFactory.java:494)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.item.ItemEntity.m_6123_(ItemEntity.java:349)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_36277_(Player.java:560)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_8107_(Player.java:527)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_8119_(Player.java:241)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.Connection.m_129483_(Connection.java:263)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/Font for invalid dist DEDICATED_SERVER [in thread "Server thread"]
        at TRANSFORMER/primalmagick@4.0.7/com.verdantartifice.primalmagick.client.books.BookHelper.<clinit>(BookHelper.java:57)
        ... 24 more
```

**Comment by daedalus4096** [comment]
I wasn't able to reproduce this issue in my test environment, but I think I've isolated the source of the mod interaction which is causing it.  A fix will be available in the next release, currently planned as v4.0.8, which should be available in the near future.  Should you encounter this issue again, please file a new ticket with fresh logs.  Thanks for the bug reports and helping to make Primal Magick better!
