### ISSUE TITLE
Tip to help 

### ISSUE THREAD

**Issue by Nicko009** [daedalus4096/PrimalMagick#225]
Hello, I'm Nicolas, I really like your developed mod and I would like to collaborate by creating a Spanish translation of it. If you like, don't give me access to the project. I'll send you the txt file in Spanish. I'm not asking for anything more than the credit, if that's the case. What seems good to you?

I have a preview with the items, I just can't find the content of the book

From experience I don't have much experience as a modder but I have experience as a programmer, I am a computer systems engineer

**Comment by daedalus4096** [comment]
Hello, Nicolas, and thank you for reaching out!  I'd love to have your help in translating Primal Magick to Spanish.  Currently, localization for the project is being managed through Crowdin.  You should be able to use this link to be added to the project as a translator: https://crowdin.com/project/primal-magick/invite?h=37047756fec466f2394c515cb0fdab3b1894910.  If that doesn't work, send your email address to the email address on my profile and I'll invite you manually.  Thanks, and I'm looking forward to working with you!
