### ISSUE TITLE
Crash my server

### ISSUE THREAD

**Issue by Nicko009** [daedalus4096/PrimalMagick#232]
Internal Exception: java.lang.NullPointerException: Cannot  invoke "com.verdantartifice.primalmagick.common.theorycrafttingweights.IWeightsFunctionSerializar.fromNerwork(net.minecraft.network.FriendlyByteBuf)" because "serializer" is null

**Comment by daedalus4096** [comment]
Well, it's certainly not supposed to do that, but I could use some more to go on.  Could you upload the server's crash report and/or log file to a site like https://pastebin.com/ and paste the link here?  Thanks.

**Comment by daedalus4096** [comment]
Without more information, I'm not able to reproduce this issue in my test environment.  So, I've added some guards around the area that your log line suggests is responsible.  This change will be available in the next release, currently planned as 4.0.9.  If you encounter this issue again, please file a new ticket with a complete crash report and/or log file from the server.
