### ISSUE TITLE
server crash on startup - 3.2.1

### ISSUE THREAD

**Issue by ErisaFirehawk** [daedalus4096/PrimalMagick#238]
had a random crash and now the server crashes on start. i am running this cia the occultcraft modpack. My host support is who pointed me to this mod. heres the crash report.
[crash-2023-12-25_23.10.44-server.txt](https://github.com/daedalus4096/PrimalMagick/files/13768190/crash-2023-12-25_23.10.44-server.txt)

**Comment by daedalus4096** [comment]
As we discussed on Discord, I don't believe this to be something I can give you a workaround for.  Older versions of the mod, like this one, had some big legacy performance issues still plaguing them in heavy mod packs.  Your best bet is to update to the latest version of the mod for Minecraft 1.20.1, which features some big improvements in that area, such as asynchronous affinity loading to prevent this sort of crash.  Thank you, and I'm sorry I don't have a better answer for you.
