### ISSUE TITLE
Issue found when trying to craft spell

### ISSUE THREAD

**Issue by PlaceHolderUserName2** [daedalus4096/PrimalMagick#240]
This is on 1.12.2 multiplayer server

3.2.1

this is on a server that i do not own running a modpack

whenever i attempt to craft a spell, it does not log the spell as crafted, is there a way around this? can i contact an admin of the server to somehow give me the statistics for it, is there another minor fix i can do to get around this? preferably without just changing the version

i cannot progress in the mod without a fix for this as it is a blockade to an entire wing of the book

**Comment by daedalus4096** [comment]
Hello, and I apologize for the error you've encountered.  Yes, there's a workaround.  You can have an admin of the server run the following command to grant you credit for crafting a spell:

/pm stats <playername> set primalmagick:spells_crafted 1

Should that not work, an admin can simply grant you credit for the research you're trying to complete, using the following command:

/pm research <playername> grant <researchname>

In this case, "researchname" would the internal name of the research you're trying to complete, likely either "WAND_INSCRIPTION" or "EXPERT_SORCERY" given the statistic you're blocked on.  Minecraft's command auto-completion should guide your admin in either case.  Should you decide to update the version you're using, rest assured that this class of bug was fixed as of Minecraft 1.20.1.

Thank you for the bug report, and I hope you continue to enjoy the mod.

**Comment by PlaceHolderUserName2** [comment]
I found a usable fix. I was reading through your bug fixes for the later versions and I noticed a shift click issue, oddly enough the only way to craft a spell is to shift click, if you manually pick it up, it won't count it. So I found a fix without needing to get the server admin on.
