### ISSUE TITLE
Interaction with Ars Nouveau

### ISSUE THREAD

**Issue by MrBrwd** [daedalus4096/PrimalMagick#243]
Server crashes when interacting with Scribe's Table when interacted with with Spellbook, (Apprentice, Mage, and Archmage, untested with Creative) when they are in the same chunk as Primal Magick workbenches. Known set ups include Basic Calcinator, Research Table, Analysis Table, Arcane Workbench, and Wand Charger. Ars Nouveau is 1.20.1-4.7.4 and Primal Magick is 4.0.8

[crash-2024-01-08_19.00.38-server.txt](https://github.com/daedalus4096/PrimalMagick/files/13867377/crash-2024-01-08_19.00.38-server.txt)

**Comment by dreamlibrarian** [comment]
Looks like this might be fixed in #241?

**Comment by daedalus4096** [comment]
Yeah, I think this is the same bug, alright.  The capability provider wasn't safely handling null directions being passed in, but that should be fixed in 4.1.0-beta for Minecraft 1.20.2.
