### ISSUE TITLE
Ritual doesn't work (MC version 1.20.1, forge)

### ISSUE THREAD

**Issue by Eos109** [daedalus4096/PrimalMagick#247]
In this layout the Ritual is saying it can't find a light grey ritual candle (to the point I played two of them but still got the same error)
 the dowsing rod says that it's at neutral stability
![2024-01-23_19 43 40](https://github.com/daedalus4096/PrimalMagick/assets/111760018/c48bb73a-682c-4ec4-ab09-c59ebd8b6102)

**Comment by daedalus4096** [comment]
It looks like all of your candles are lit already, which would cause the problem that you're seeing.  An important part of all rituals is activating your props when you're told to do so, but not before.  When you start a ritual, props need to be in their inactive state; so candles would have to be unlit, incense braziers doused, etc.  Already active props, such as lit candles, won't work.  Try snuffing at least one of your candles and try again.
