### ISSUE TITLE
Light spell casted on torch crashes server

### ISSUE THREAD

**Issue by LvInSaNevL** [daedalus4096/PrimalMagick#267]
Here are some version numbers for you

- Primal Magick: 4.0.9
- Server OS: Ubuntu 20.04.4 LTS
- Docker: 26.1.2, build 211e745
    - I am running all of this in a Docker container using [ITZG's](https://github.com/itzg/docker-minecraft-server) container

I had a friend who recently unlocked the light spell so we tried putting it on a torch, and immediately when we did that the server hard crashed and the docker container needed to be restarted. Although, when we get back on the server, it does seem like the spell took effect since the torch is brighter than normal. We were able to replicate this issue 2 or 3 times before we decided to stop crashing the server. 

I have included the relevant section of the Minecraft server [logs](https://github.com/daedalus4096/PrimalMagick/files/15436399/logs.txt), as well as the [crash dump](https://github.com/daedalus4096/PrimalMagick/files/15436398/crash_report.txt) from the first crash. It seems like Java crashes when you try to set the "facing" property of the torch. 

This isn't *too* important since we can just not cast the light spell on a torch, but I figured I would bring it up to you. 

[crash_report.txt](https://github.com/daedalus4096/PrimalMagick/files/15436398/crash_report.txt)
[logs.txt](https://github.com/daedalus4096/PrimalMagick/files/15436399/logs.txt)
set the "facing" property of the torch.

**Comment by daedalus4096** [comment]
This bug should be fixed in the next release, currently slated to be v5.0.1-beta for Minecraft 1.21.1. Thank you for the report!
