### ISSUE TITLE
Clientside functions loop with tooltip

### ISSUE THREAD

**Issue by NiNeDelixe** [daedalus4096/PrimalMagick#277]
I play on version 1.19.2 and when i press shift get a lagspike
Spark show this is because functions calls looped
![image](https://github.com/user-attachments/assets/9c08829c-eecc-48d6-b5df-b53ee33b1fb6)
[SparkProfile.zip](https://github.com/user-attachments/files/16203888/SparkProfile.zip)

Mods:
  [✔️] a_good_place-1.19-1.1.0.jar
  [✔️] abnormals_delight-1.19.2-4.1.2.jar
  [✔️] AbundantAtmosphere-1.19.2-1.8.2-beta.jar
  [✔️] abyssal_decor_1.19.2_0.1.4.jar
  [✔️] ad_astra-forge-1.19.2-1.12.7.jar
  [✔️] AdditionalPlacements-1.19.2-1.8.0.jar
  [✔️] advancementscreenshot-1.19.2-4.7.jar
  [✔️] ae2qolrecipes-forge-1.18.x-1.20.x-1.2.0.jar
  [✔️] AIOTBotania-1.19.2-3.0.2.jar
  [✔️] alloyed-1.19.2-v1.5a.jar
  [✔️] Animation_Overhaul-forge-1.19.x-1.3.0.jar
  [✔️] Any_Lanterns_1.1_1.19.2.jar
  [✔️] Applied-Botanics-forge-1.4.6.jar
  [✔️] appliedenergistics2-forge-12.9.9.jar
  [✔️] Aquaculture-1.19.2-2.4.17.jar
  [✔️] architectury-6.6.92-forge-1.19.2.jar
  [✔️] ArmorStatues-v4.0.8-1.19.2-Forge.jar
  [✔️] AutoRegLib-1.8.2-55.jar
  [✔️] badpackets-forge-0.2.3.jar
  [✔️] betterchunkloading-1.19.2-2.5.jar
  [✔️] betterfpsdist-1.19.2-4.1.jar
  [✔️] BetterPingDisplay-1.19-1.1.jar
  [✔️] biomancy-forge-1.19.2-2.3.2.0.jar
  [✔️] biomebackport-1.1.5-1.19.2.jar
  [✔️] blockcarpentry-1.19.2-0.3.1.5.jar
  [✔️] blueprint-1.19.2-6.2.0.jar
  [✔️] Botania-1.19.2-440-FORGE.jar
  [✔️] BotanicAdditions-1.19.2-19.3.6.jar
  [✔️] botarium-forge-1.19.2-1.9.2.jar
  [✔️] BuildersDelight-1.19.2-v.1.1.jar
  [✔️] Butters-CreateQuarkRecipe-1.19.2.jar
  [✔️] caelus-forge-1.19.2-3.0.0.6 (1).jar
  [✔️] cakescosmetics-1.19.2-0.2.0.jar
  [✔️] canary-mc1.19.2-0.3.3.jar
  [✔️] castleblocks-1.0.9.1-forge-1.19.2.jar
  [✔️] cc-tweaked-1.19.2-1.101.4.jar
  [✔️] Chimes-v2.0.1-1.19.2.jar
  [✔️] chromatic_construct-1.1.0.jar
  [✔️] chromaticarsenal-1.19.2-1.18.0.jar
  [✔️] clientcrafting-1.19.2-1.6.jar
  [✔️] cloth-config-8.3.115-forge.jar
  [✔️] CoffeeDelight-Forge-1.19.2-1.4.jar
  [✔️] collective-1.19.2-7.64.jar
  [✔️] ColorfulAzaleas-forge-1.19.2-2.3.1.jar
  [✔️] colorize-1.19.2-forge-1.4.0.jar
  [✔️] CommonCapabilities-1.19.2-2.9.1.jar
  [✔️] configured-2.1.1-1.19.2.jar
  [✔️] connectivity-1.19.2-4.6.jar
  [✔️] constructs_casting-1.1.2.jar
  [✔️] Controlling-forge-1.19.2-10.07.jar
  [✔️] copiesandcats-0.0.2a-1.19.2.jar
  [✔️] Copperative 1.19.2--1.1.0.jar
  [✔️] coroutil-forge-1.19.2-1.3.6.jar
  [✔️] CosmeticArmorReworked-1.19.2-v1a.jar
  [✔️] CrabbersDelight-1.19.2-1.1.4.jar
  [✔️] crab-forge-1.19.2-1.0.1.jar
  [✔️] CraftPresence-2.4.3+1.19.2.jar
  [✔️] create_ca-2.0b - 1.19.2.jar
  [✔️] create_central_kitchen-1.19.2-for-create-0.5.1.f-1.3.11.c.jar
  [✔️] create_connected-0.8.2-mc1.19.2-all.jar
  [✔️] create_crushing_quartz-forge-1.19.2-1.0.0.jar
  [✔️] create_enchantment_industry-1.19.2-for-create-0.5.1.f-1.2.9.e.jar
  [✔️] create_factory-0.0.2-1.19.2.jar
  [✔️] create_misc_and_things_-1.19.2_4.0A.jar
  [✔️] create_more_copycats-1.19.2-1.1.0.jar
  [✔️] Create_mortar1.19.2v0.1.9.jar
  [✔️] create_netherless-1.19.2-1.3.jar
  [✔️] create_ore_excavation_plus-0.2.2-1.19.2.jar
  [✔️] create_power_loader-1.5.0-mc1.19.2.jar
  [✔️] create_recycle_1.0.2_forge_1.19.2.jar
  [✔️] create_tweaked_controllers-1.19.2-1.2.4.jar
  [✔️] create-1.19.2-0.5.1.f.jar
  [✔️] createappliedkinetics-1.3.2-1.19.2.jar
  [✔️] createbigcannons-forge-1.19.2-0.5.4.jar
  [✔️] createcafe-1.2.4-1.19.2.jar
  [✔️] CreateCasing-1.19.2-1.6.1.jar
  [✔️] create-confectionery1.19.2_v1.0.9.jar
  [✔️] createdeco-1.3.3-1.19.2.jar
  [✔️] Create-Dreams-n-Desires-1.19.2-0.2.5b.PREBETA.jar
  [✔️] creategoggles-1.19.2-0.5.5.g-[FORGE].jar
  [✔️] createindustry-0.9.0d-1.19.2.jar
  [✔️] create-new-age-forge-1.19.2-1.1.2.jar
  [✔️] createoreexcavation-1.19-1.2.3.jar
  [✔️] create-stuff-additions1.19.2_v2.0.4a.jar
  [✔️] CreativeCore_FORGE_v2.11.28_mc1.19.2.jar
  [✔️] crittersandcompanions-1.19.2-2.1.2.jar
  [✔️] CrosshairBobbing-1.6-1.20.2-1.16.2.jar
  [✔️] CTM-1.19.2-1.1.6-8.jar
  [✔️] CullLessLeaves-Reforged-1.0.5.jar
  [✔️] cupboard-1.19.2-2.3.jar
  [✔️] curios-forge-1.19.2-5.1.6.1.jar
  [✔️] CyclopsCore-1.19.2-1.19.0.jar
  [✔️] dae2-1.19.2-0.0.1-all.jar
  [✔️] dbExtended-1.19.2-6.0.1.jar
  [✔️] DeeperCaves-1.19.2-1.2.3.jar
  [✔️] Delightful-1.19.2-3.4.1.jar
  [✔️] design_decor-0.4-1.19.2.jar
  [✔️] drawerfps-1.19.2-1.8.jar
  [✔️] drizzleproof-1.19.2-1.0.0.jar
  [✔️] dsbg-1.0-1.19.2.jar
  [✔️] effective_fg-1.3.4.jar
  [✔️] elytras-forge-1.19.2-1.0.1.jar
  [✔️] Enchanted-forge-1.19.2-2.0.3.jar
  [✔️] EnchantIcon-Forge-1.19.2-1.1.1-13.jar
  [✔️] EnhancedBlockEntities-Reforged-1.19.2-0.8.0.jar
  [✔️] EnigmaticLegacy-2.26.5.jar
  [✔️] Entity_Collision_FPS_Fix-forge-1.18.2-1.0.0.jar
  [✔️] entityculling-forge-1.6.1-mc1.19.2.jar
  [✔️] EpicFight-19.5.25.jar
  [✔️] Excessive-Building-Forge-1.19.2-2.0.3.1.jar
  [✔️] explosiveenhancement-1.0.0.jar
  [✔️] exposure-1.19.2-1.6.0-forge.jar
  [✔️] extendedgears-2.1.1-1.19.2-0.5.1.f-forge.jar
  [✔️] FarmersDelight-1.19.2-1.2.4.jar
  [✔️] FarmersDelightPlus-1.19.2-1.2.0.jar
  [✔️] FarmersRespite-1.19-2.0.jar
  [✔️] farsight-1.19.2-3.6.jar
  [✔️] Fastload-Reforged-mc1.19.2-3.4.0.jar
  [✔️] FixMySpawnR-forge-1.19.2-1.1.2.jar
  [✔️] forbidden_arcanus-1.19.2-2.1.5.jar
  [✔️] forcegl20-forge-1.2.0+1.17.x-1.21.x.jar
  [✔️] forgetmechunk-1.0.4-1.18.X-1.19.X.jar
  [✔️] fruitsdelight-0.5.7-1.19.2.jar
  [✔️] FruitTrees-1.19.2-forge-6.3.1.jar
  [✔️] Galosphere-1.19.2-1.3.0-Forge.jar
  [✔️] gardens-of-the-dead-forge-2.0.2.jar
  [✔️] geckolib-forge-1.19-3.1.40.jar
  [✔️] geologicexpansion-1.0.1-1.19.2-forge.jar
  [✔️] GeophilicReforged-v1.2.0-1.20.2.jar
  [✔️] goldenfood-1.19.2-2.0.0.jar
  [✔️] HammerLib-1.19.2-19.3.82.jar
  [✔️] handcrafted-forge-1.19.2-2.0.6.jar
  [✔️] Hand-Magic-1.1-1.19.2-Forge.jar
  [✔️] healpgood-1.3.3F-1.19.2.jar
  [✔️] hearth_and_home-forge-1.19.2-1.0.1.jar
  [✔️] hearths-v1.0.0-mc1.19u1.19.3.jar
  [✔️] hexcasting-forge-1.19.2-0.10.3.jar
  [✔️] HexCircus-1.1.1.jar
  [✔️] hexiron-forge-1.19.2-0.1.0.jar
  [✔️] IC2Classic-1.19.2-2.0.9.2.jar
  [✔️] ic2cuumatter-1.19.2-1.3.2.jar
  [✔️] ImmediatelyFastReforged-1.19.2-1.1.10.jar
  [✔️] IntegratedCrafting-1.19.2-1.1.6.jar
  [✔️] IntegratedDynamics-1.19.2-1.21.2.jar
  [✔️] IntegratedREST-1.19.2-1.1.9.jar
  [✔️] IntegratedTerminals-1.19.2-1.4.11.jar
  [✔️] IntegratedTunnels-1.19.2-1.8.24.jar
  [✔️] irons_spellbooks-1.19.2-3.2.0.jar
  [✔️] ItemLocks-Forge-1.19.2-1.3.8.jar
  [✔️] ItemPhysic_FORGE_v1.6.7_mc1.19.2.jar
  [✔️] ItShallNotTick-1.0.11-build.35.jar
  [✔️] jei-1.19.2-forge-11.6.0.1020.jar
  [✔️] just_dandy-1.19.2-1.0.2.jar
  [✔️] JustEnoughFarmersRecipes-1.19-1.0.1.jar
  [✔️] JustEnoughResources-1.19.2-1.2.3.243.jar
  [✔️] Kiwi-1.19.2-forge-8.3.6.jar
  [✔️] kotlinforforge-3.12.0-all-1.19.2.jar
  [✔️] krystal_core-1.19.2-1.0.1.jar
  [✔️] krystalsmaterialcompats-1.0.r.0-forge-mc1.19.2.jar
  [✔️] labels-1.19.2-1.10.jar
  [✔️] lazydfu-1.19-1.0.2.jar
  [✔️] leaky-1.19.2-1.3.jar
  [✔️] lemoned-1.0.0-1.19.jar
  [✔️] lightspeed-1.19.2-1.0.5.jar
  [✔️] limitedchunks-1.19.2-3.9.jar
  [✔️] locksmith-forge-1.1.1-1.19.2_1.jar
  [✔️] logicchips-1.19.2-2.1.0-forge.jar
  [✔️] lucent-1.19.2-1.4.1.jar
  [✔️] luki-s-grand-capitals-0.7-forge-1.19-1.20.1.jar
  [✔️] MaFgLib-0.1.12-mc1.19.2.jar
  [✔️] Mantle-1.19.2-1.10.36.jar
  [✔️] meaningfulmaterials-1.0.0-beta.2.jar
  [✔️] megane-forge-19.2.2.jar
  [✔️] memoryleakfix-forge-1.17-1.1.5.jar
  [✔️] merequester-forge-1.19.2-1.1.4.jar
  [✔️] MissingWilds-forge-1.19.2-1.2.0-beta.2.jar
  [✔️] mobtimizations-forge-1.19.2-1.0.0.jar
  [✔️] moderntrainparts-mc1.19.2-0.2.2-forge.jar
  [✔️] moonlight-1.19.2-2.3.6-forge.jar
  [✔️] moredelight-2024.06.30-1.19.2-forge.jar
  [✔️] MyNethersDelight-1.19-0.1.1.jar
  [✔️] neapolitan-1.19.2-4.1.0.jar
  [✔️] Necronomicon-Forge-1.4.2.jar
  [✔️] nemos-mossy-blocks-1.4.2-1.19.2.jar
  [✔️] new_120_content-1.19.2-2.0.jar
  [✔️] NotEnoughBlocks-1.8.0-1.19.2.jar
  [✔️] Nullscape_1.19.3_v1.2.2.jar
  [✔️] obscure_api-9-1.19.jar
  [✔️] obscure_tooltips-1.0.api9-1.19.jar
  [✔️] Oceans-Delight-v1.0.2-1.19.2.jar
  [✔️] oculus-mc1.19.2-1.6.9.jar
  [✔️] opulence-1.19.2-0.2.0.jar
  [✔️] packetfixer-forge-1.4.2-1.19-to-1.20.1.jar
  [✔️] Patchouli-1.19.2-77.jar
  [✔️] paucal-forge-1.19.2-0.5.0.jar
  [✔️] Ping-Wheel-1.9.1-forge-1.19.2.jar
  [✔️] placeableblazerods-1.19.2-3.5.jar
  [✔️] Placebo-1.19.2-7.3.4.jar
  [✔️] player-animation-lib-forge-1.0.21.19.2.jar
  [✔️] pluto-mc1.19.2-0.0.9.jar
  [✔️] pollen-forge-2.1.0-1.19.2.jar
  [✔️] polyeng-forge-0.1.1-1.19.2.jar
  [✔️] polymorph-forge-0.46.61.19.2.jar
  [✔️] Potion-Blender-1.19.2-FORGE-1.1.0.jar
  [✔️] primalmagick-3.2.1.jar.disabled (disabled)
  [✔️] productivebees-1.19.2-0.10.7.2.jar
  [✔️] protection_pixel-1.19.2-1.0.0.jar
  [✔️] PuzzlesLib-v4.4.3-1.19.2-Forge.jar
  [✔️] Quark-3.4-418-1.19.2.jar
  [✔️] randomshit.rar
  [✔️] rayon-forge-1.7.1+1.19.2.jar
  [✔️] recipeessentials-1.19.2-3.2.jar
  [✔️] reddens_stone_lanterns_1.0.3-forge1.19.2.jar
  [✔️] redeco-1.5.0-1.19.2.jar
  [✔️] reforgium-1.0.12a.jar
  [✔️] resourcefulconfig-forge-1.19.2-1.0.20.jar
  [✔️] resourcefullib-forge-1.19.2-1.1.24.jar
  [✔️] restApi+-+0.7+-+1.19.2+-+Forge.jar
  [✔️] reworked_sleep_to_night-1.0.2.jar
  [✔️] rsec-1.0-1.19.2-forge.jar
  [✔️] rubidium-mc1.19.2-0.6.2c.jar
  [✔️] runology-2.0.0-forge-1.19.2.jar
  [✔️] S33R-Iris-Azalea-ver-19.3.5.jar
  [✔️] Saros-Create-Addon-1.19.2-1.9-[Forge].jar
  [✔️] saturn-mc1.19.2-0.1.4.jar
  [✔️] sculktransporting-1.19.2-1.1.jar
  [✔️] sculpt-1.19.2-v1.1.2.0.jar
  [✔️] seamless-2.2.2-forge-1.19.2.jar
  [✔️] Second-Chance-Forge-Release-1.5.1-for-Minecraft-1.19.jar
  [✔️] sfcr-1.7.6-mc1.19.2.jar
  [✔️] showcaseitem-1.19.2-1.1.jar
  [✔️] silver-birch-1.1.1-1.19.2.jar
  [✔️] simple_cream_1.19.2-1.2.2-forge.jar
  [✔️] SmartBrainLib-forge-1.19.2-1.9.jar
  [✔️] smoothbootreloaded-mc1.19.2-0.0.4.jar
  [✔️] sophisticatedcore-1.19.2-0.6.4.605.jar
  [✔️] sophisticatedstorage-1.19.2-0.9.7.765.jar
  [✔️] sound-physics-remastered-forge-1.19.2-1.4.2.jar
  [✔️] spark-1.10.37-forge.jar
  [✔️] StateObserver-forge-1.19.2-1.3.1.jar
  [✔️] Stellar-View-1.19.2-0.2.4.jar
  [✔️] StickerFrames-1.19.2-1.0.1.jar
  [✔️] stopdropnroll-1.0.0-forge.jar
  [✔️] storagedelight-1.1.1-1.19.2-forge.jar
  [✔️] supplementaries-1.19.2-2.4.20.jar
  [✔️] suppsquared-1.19.2-1.1.1.jar
  [✔️] swingthroughgrass-1.19-1.10.1.jar
  [✔️] TCIntegrations-1.19.2-2.0.21.7.jar
  [✔️] tconjei-1.19.2-1.2.0.jar
  [✔️] TConstruct-1.19.2-3.8.3.39.jar
  [✔️] tectonic-forge-1.19-2.3.5a.jar
  [✔️] TeleporterMod-v1-1.19.2.jar
  [✔️] TerraBlender-forge-1.19.2-2.0.1.166.jar
  [✔️] tia-1.19.2-1.0-forge.jar
  [✔️] Tinkers-Thinking-0.1.3.3.jar
  [✔️] upgrade_aquatic-1.19.2-5.1.0.jar
  [✔️] upgradedcore-1.19.2-4.1.0.1-release.jar
  [✔️] upgradednetherite-1.19.2-5.1.0.9-release.jar
  [✔️] usefulspyglass-forge-1.19.2-0.4.0.jar
  [✔️] valhelsia_core-forge-1.19.2-0.5.0.jar
  [✔️] venus-mc1.19.2-0.0.1.jar
  [✔️] voicechat-forge-1.19.2-2.5.1.jar
  [✔️] wallpapers-0.7b-1.19.2.jar
  [✔️] watut-forge-1.19.2-1.0.14.jar
  [✔️] weaponmaster_ydm-forge-1.19.2-4.2.3.jar
  [✔️] wetlands-1.2-1.19.2.jar
  [✔️] what_the_geck-1.19-2-1.0.3.8.jar
  [✔️] Woodster-1.2.4-1.19.2.jar
  [✔️] woodworks-1.19.2-2.2.2.jar
  [✔️] wthit-forge-5.28.2.jar
  [✔️] XaerosWorldMap_1.38.8_Forge_1.19.1.jar
  [✔️] xlpackets-1.18.2-2.1.jar
  [✔️] YungsApi-1.19.2-Forge-3.8.10.jar
  [✔️] YungsBetterNetherFortresses-1.19.2-Forge-1.0.6.jar

**Comment by daedalus4096** [comment]
I'm afraid that's a known issue with versions of the mod prior to 4.0.4 for MC 1.20.1, which introduced some performance improvements for affinity calculation. I currently have no plans to backport the fix to MC 1.19.2, so your best bet is to update your server when you can.
