### ISSUE TITLE
Crash when ars nouveau scribes table is within certain range of research table

### ISSUE THREAD

**Issue by Everflame42** [daedalus4096/PrimalMagick#280]
Version 4.0.9 of primal magick and version 4.12.4 of ars nouveau  Minecraft 1.20.1

When the ars nouveau scribes table is within range to be able to attempt to pull from the inventory of the research table when trying to make a spell the scribe's table will constantly tick, causing a crash. Within the same chunk they two are fine as long as they're far enough apart. After the first image I moved the scribe's table within 3 blocks, tried to make a light spell at the scribe's table, and the game froze and then crashed within a few seconds before I could grab a screenshot.

[crash-2024-08-06_12.32.20-server.txt](https://github.com/user-attachments/files/16513886/crash-2024-08-06_12.32.20-server.txt)
![2024-08-06_12 31 08](https://github.com/user-attachments/assets/48080439-6038-4664-a0d6-ee3073a594b6)

Edit: Got a response from the ars nouveau discord so thought I'd edit it in here.
![Screenshot 2024-08-06 133906](https://github.com/user-attachments/assets/5e638ce2-17be-46fe-be77-f54789e6d63a)

**Comment by daedalus4096** [comment]
Thank you for the report. After looking into the issue further, it looks like this bug was fixed in v4.1.0-beta of Primal Magick, the version immediately following the one you're playing on for Minecraft 1.20.2. If you encounter this issue again on that updated version, please file a new ticket.
