### ISSUE TITLE
byte buffer issue

### ISSUE THREAD

**Issue by QCalamitas** [daedalus4096/PrimalMagick#293]
hello! I'm having issues adding this mod to my minecraft server, when I try to join it I get an error message upon joining that reads "Internal Exception: io.netty.handler.codec.DecoderException: Not enough bytes in buffer, expected 110 but got 72" This is using forge version 49.1.0, on 1.20.4 I am using the mod version 4.2.0 beta.

[latest.log](https://github.com/user-attachments/files/17285538/latest.log)

**Comment by QCalamitas** [comment]
[crash-2024-10-05_20.41.02-client.txt](https://github.com/user-attachments/files/17285946/crash-2024-10-05_20.41.02-client.txt)

**Comment by QCalamitas** [comment]
[crash-2024-10-05_19.49.59-fml.txt](https://github.com/user-attachments/files/17285950/crash-2024-10-05_19.49.59-fml.txt)
[crash-2024-10-05_20.03.21-fml.txt](https://github.com/user-attachments/files/17285951/crash-2024-10-05_20.03.21-fml.txt)
[crash-2024-10-05_20.11.56-fml.txt](https://github.com/user-attachments/files/17285952/crash-2024-10-05_20.11.56-fml.txt)
[crash-2024-10-05_20.41.02-client.txt](https://github.com/user-attachments/files/17285953/crash-2024-10-05_20.41.02-client.txt)
[crash-2024-10-05_20.49.44-client.txt](https://github.com/user-attachments/files/17285954/crash-2024-10-05_20.49.44-client.txt)

**Comment by daedalus4096** [comment]
So I took a look at the five crash reports you sent. The three FML crash reports all indicate a mod loading problem with a mod called Dragon Mounts: Legacy. It looks like you were trying a few different versions of it and having problems with them. The two client crash reports cite registry errors with the mods Fantasy Metals and Macaw's Furniture. It looks like they were failing to register certain blocks, specifically Mythril Blocks and Oak Drawers respectively.

I don't see anything in any of the crash reports that talks about the netty buffer DecoderException that you originally cited. It's possible that's just a secondary effect of one of these other errors, though; you can't always rely on accurate reporting when the system is already crashing. I also don't see anything about Primal Magick failures in any of the crash reports.

Unfortunately, I'm afraid that none of this is anything that I can help you with. I'd recommend that you take a little time to make sure that the versions of the mods you're using are all compatible with the versions of Minecraft and Forge that you're running on. Sorry I can't be more help.
