### ISSUE TITLE
Infernal Pixie ritual recipe

### ISSUE THREAD

**Issue by kurushimi0** [daedalus4096/PrimalMagick#301]
In v4.0.9 for Minecraft 1.20.1, the ritual recipe for Infernal Pixies uses Infernal Dust instead of an Infernal Shard. Since this sets it apart from all other pixies at that level, I figured it might be unintended.

**Comment by daedalus4096** [comment]
Thank you for the report, but this is intended behavior. Because Infernal pixies explode and have to be resuscitated between every use, it didn't feel fair to charge a full shard to summon them in the first place.
