### ISSUE TITLE
Analysis Table Doesn't Return Unused Items On Exit

### ISSUE THREAD

**Issue by darkpoetcc** [daedalus4096/PrimalMagick#55]
If you put an item in the Analysis Table, and then exit the station, rather than using the station to analyze the item placed inside, the item is lost.  There is nothing written in the log file when this occurs.

**Steps to Reproduce**
1) Open the Analysis Table UI
2) Insert an item, but DO NOT click the magnifying glass to analyze the item
3) Exit the Analysis Table UI
4) Note the item is not returned, and upon re-opening the Analysis Table UI, is not there, either

NOTE:  This does not occur with the other stations I have used.  The Spellcrafting Altar and Arcane Workbench return your items to you.  The Research Table and Essence Furnace retain the items you place into their UI.

**Versions**
Minecraft 1.17.1
Forge 37.0.104
Primal Magick 0.1.0-beta JAR

**Comment by daedalus4096** [comment]
Fixed in the next build.  Thanks for the report!
