### ISSUE TITLE
Leaves don't properly decay with Fast Leaf Decay.

### ISSUE THREAD

**Issue by AnotherVagabond** [daedalus4096/PrimalMagick#59]
The leaves for both the moonwood and sunwood trees only decay at the normal rate even with Fast Leaf Decay installed (it's the 1.18 version of FLD, but it works on all the other trees in the pack, including modded trees).

Minecraft: 1.18.1
Forge: 39.0.8
Primal Magick: 2.0.0
Fast Leaf Decay: 27

**Comment by daedalus4096** [comment]
Unfortunately, I don't believe I can fix this on my end.  For various technical reasons, the sunwood and moonwood leaves blocks don't use the standard Minecraft leaves code.  FLD appears to only work with blocks that do.  I can file a ticket with the FLD developer to suggest an alternate method they could use that would work with sunwood and moonwood leaves, but there's no guarantee they'll act upon it.  Sorry.

**Comment by AnotherVagabond** [comment]
Okay, thanks for the response! It's not really a huge deal either way, but I figured I'd mention it in case it was an easy fix.
