### ISSUE TITLE
StackOverflowError when looking at extended tooltip of any item made with glass with create mod installed

### ISSUE THREAD

**Issue by IIaMoCLitTMW** [daedalus4096/PrimalMagick#60]
Crash occurs when trying to calculate affinities for items made out of glass

Steps to reproduce:
Open any inventory containing any item crafted using Glass
Mouse over said item
Press shift

[crash-2021-12-28_19.12.10-client.txt](https://github.com/daedalus4096/PrimalMagick/files/7785908/crash-2021-12-28_19.12.10-client.txt)

versions:
MC - 1.18.1
Forge - 39.0.8
Create - v0.4a
Flywheel - 0.4.2-rc
Primal Magick - 2.0.0-beta

Fun fact:
If you add Optifine to the mix, then the game doesn't crash but causes large lag spikes and the tooltip doesn't show at all

**Comment by daedalus4096** [comment]
This issue should be fixed as of version 2.0.2 of Primal Magick.  Please file a new ticket if you encounter the issue again.  Thank you for filing this ticket and helping me make the mod better!
