### ISSUE TITLE
[Suggestion] Grimoire usability enhancement

### ISSUE THREAD

**Issue by DaRetroCat** [daedalus4096/PrimalMagick#61]
Through my usage of the mod, I've found the grimoire a bit difficult and tedious to use so I've thought of some suggestions to make it more useable in my humble opinion, ill go from the smallest suggestion to the largest suggestion in scope to make this more readable.

**<1> Grimoire being able to remember the last opened page.**
Currently, the grimoire doesn't remember the last page you had opened and just opens the main page which makes re-consulting entries annoying as you have to re-navigate to the page each time you open the grimoire again which gets tedious quickly so by allowing the grimoire to remember the last page and return to it on reopen would make it a lot less tedious to progress.

**<2> Item symbols next to entries names.**
![image](https://user-images.githubusercontent.com/71947170/147730458-b26570ab-6f18-4781-a74e-10cef8951daa.png)
 As seen in my crude example the difference is night and day having actual symbols/items attached to each entry text makes it so much easier to identify and find entries you want. while I doubt it would be easy to code in I think the addition would make the grimoire a lot more enjoyable to use.

**<3> Enhanced main page.**
![image](https://user-images.githubusercontent.com/71947170/147730466-e0683492-28a4-4d99-b87c-d14ce35a3967.png)
Currently, the main page of the book is a bit dull being simple black text so taking the same principle of the last suggestion and applying it to the main page would be ideal along with making discipline text larger to better fit the main page.

**Comment by daedalus4096** [comment]
These three enhancements will be available in the next build of Primal Magick, currently planned as v2.0.5.  Thanks for the suggestions!
