### ISSUE TITLE
Holding shift over some items in inventories freezes the game for ~10-30 seconds.

### ISSUE THREAD

**Issue by AnotherVagabond** [daedalus4096/PrimalMagick#62]
It doesn't always happen, but I haven't been able to find any specific list of items that causes it, it just seems to randomly happen while holding shift over an item, either to expand some tooltips or just move items between inventories. It looks like it's an OptiFine compatibility, but I don't know if it's something you can fix on your end or not, so I'll throw it up here anyway since there are no OptiFine alternatives for Forge 1.18.1 yet.

The error it throws up makes the .log file too big for Pastebin, so this just includes the error itself.
https://pastebin.com/QXCTkh5K

**Comment by Febilian** [comment]
For what it is worth, I have also been experiencing this *without* Optifine installed.

**Comment by AnotherVagabond** [comment]
I believe I did have Create installed, so it probably is the same issue. I vaguely remember working with some glass stuff for Ars Nouveau at the time I noticed the lag spikes, so it could very well have been the items with glass in them that was doing this.

**Comment by daedalus4096** [comment]
This issue should be fixed as of version 2.0.2 of Primal Magick.  Please file a new ticket if you encounter issue again.  Thank you for filing this ticket and helping me make the mod better!
