### ISSUE TITLE
Mod compat issues

### ISSUE THREAD

**Issue by willtarax** [daedalus4096/PrimalMagick#63]
Just had a problem with gooey beef from Gobber2. One of my players picked it up and when he passes over it with his curser he gets booted from the server.

This is the crash report https://pastebin.com/gPZKiiph

Reached out to Gobber, and their response was 
"kwpugh — Today at 2:05 PM
First I've seen.  Looking at the report it seems to be Primal Magick writing "affinity data" to items.
Will Tarax — Today at 2:05 PM
Ah
Shoot. Thanks I'll reach out to them 🙂
kwpugh — Today at 2:07 PM
GooeyBeef is a simple food item, not sure what that mod or Harder Recipes is trying to write to it"

Any idea?

**Comment by daedalus4096** [comment]
This issue should be fixed as of version 2.0.2 of Primal Magick.  Please file a new ticket if you encounter issue again.  Thank you for filing this ticket and helping me make the mod better!
