### ISSUE TITLE
Spirit lantern variation of sun lamp does not work in crafting table

### ISSUE THREAD

**Issue by Shocktrooper** [daedalus4096/PrimalMagick#64]
Spirit lantern variation of sun lamp does not work in crafting table when put inside of the arcane workbench

![image](https://user-images.githubusercontent.com/2646851/149072023-ff896be4-3e10-49e0-92ee-0da7148e31c9.png)

**Comment by daedalus4096** [comment]
This bug should be fixed in the next release (2.0.3).  Thank you for reporting this issue and helping me make the mod better!
