### ISSUE TITLE
Functional blocks with a persistent inventory do not retain their contents after quitting the game and then rejoining a world

### ISSUE THREAD

**Issue by Febilian** [daedalus4096/PrimalMagick#65]
I have observed this with the Essence Furnace and Basic Calcinator(lost their fuel), the Wand Charger(lost an early game wand I put in it), and the Research Table(the ink and paper that was in it). I wasn't sure what had happened at first, but then I tested a hunch by leaving something inconsequential inside one of these blocks(namely a single piece of paper in the research table), saving and quitting, and then rejoining my world - it was indeed gone.

I haven't tested comprehensively with every block variant but I suspect this happens with any block that you can leave items in, which seems like a pretty critical bug.

This was observed in a single player setting, but I wouldn't be surprised if it also occurred on a server whenever the server shuts down and then starts again. 

``Forge 39.0.19``
``Primal Magick 2.0.2``

**Comment by daedalus4096** [comment]
This should be fixed in version 2.0.3.  Thank you for reporting this issue and helping me make the mod better!
