### ISSUE TITLE
JEI Integration and Scanning Suggestion

### ISSUE THREAD

**Issue by willtarax** [daedalus4096/PrimalMagick#66]
Is there planned JEI integration? I pull an item up in JEI and it will not show me the recipe.

Is there a way to add to an items tooltip if it has been put through the scanning table?

**Comment by daedalus4096** [comment]
I'd certainly like to add JEI integration, I just haven't gotten around to it yet.  I'm afraid that I don't understand your second request, however.  When you hold shift over an item to view its affinities, the mod will, by default, display "Affinities: Unknown" if you have not yet analyzed the item at the Analysis Table or via other means.  So if you can see the item's affinities in its tooltip, then you've already scanned it.  Does that satisfy what you're asking for?

**Comment by daedalus4096** [comment]
JEI support has now been added in v2.0.4.
