### ISSUE TITLE
Shift clicking to complete runescribe and move to inventory does not increment runescribing statistic

### ISSUE THREAD

**Issue by Shocktrooper** [daedalus4096/PrimalMagick#67]
As the title states if you hold shift and runescribe an item it does not increment the statistic in the grimoire.  This was a little disappointing to find as I was grinding out the amount of runescribed items needed for supreme runeworking. 

I have not looked at other instances like this but I believe other types of crafting does this same thing if you do shift click to finish and move to inventory.  For example sorcery and magitech items crafted

**Comment by daedalus4096** [comment]
Runescribing and spellcrafting should now properly increment the appropriate statistics as of v2.0.4.  Please let me know (in a new ticket) if you find any other instances of statistics not being properly updated when crafting.  Thanks for reporting the issue and helping me to make the mod better!
