### ISSUE TITLE
Provide a way to keep all attunements maxed forever

### ISSUE THREAD

**Issue by Shocktrooper** [daedalus4096/PrimalMagick#70]
While its cool that we can temporarily attune via ambrosia it has a few downsides that makes it just a pain to keep up with late game.
1. It de-attunes all other Attunements
2. Temporary
3. More of a nuisance in the endgame than it is worth to make

I have unlocked everything in my grimoire and was surprised to find that there was varying degrees of permanent attunement from my sources without explanation as to what I needed to gain more attunement in those that were lacking.  Furthermore it I seemed I could not max out all of my attunements at the same time and keep those maxed permanently.  This would bee a cool endgame thing to do with either some special all powerful ambrosia or a new item that made it so I did not have to worry about losing attunement and keeping them all maxed at the same time

**Comment by daedalus4096** [comment]
I don't believe that this is something that I want to do.  When I designed attunements, I wanted them to present the player with some choices about which bonuses they wanted to aspire to.  Careful ambrosia use will let you reach maximum level on two of them permanently, with most others being temporarily attainable.  Allowing them all to be capped feels like it would just make them another grind for the player to slog at.  Thank you for this suggestion, though, as well as your others.  I appreciate your desire to help me make the mod better for players.

**Comment by Shocktrooper** [comment]
@daedalus4096 No problem! I will have to say that a majority of players on my server shared my same sentiment as once they have went through to the endgame of primal magick they feel like they can't stay there and have to constantly come back to doing rituals to attune which is also a grind that most other mods endgame items prevent from happening once there
