### ISSUE TITLE
On server crash (and potentially a basic shutdown) inventories of Primal Magick Blocks are cleared

### ISSUE THREAD

**Issue by Shocktrooper** [daedalus4096/PrimalMagick#72]
I have noticed my wand disappearing from wand chargers, fuel/dusts disappearing from calcinators, honey/wax disappearing the magical centrifuge, etc. when my server crashes and potentially on a standard shutdown.  This is different from chests or furnaces that seem to always retain their inner inventory when the server goes down.  This causes a potential issue for multiplayer players on servers when they leave something running and then the next thing they know the block has been emptied out with no trace of what was put in it

**Comment by Febilian** [comment]
Could you check whether you're using an updated version? This sounds like the issue I was having #65 but if it's still happening on the most recent version of the mod on Curseforge then it might be different.

**Comment by daedalus4096** [comment]
This sounds like a bug that I recently fixed, as of version 2.0.3, if I remember correctly.  What version are you using?

**Comment by Shocktrooper** [comment]
I was using 2.0.2 when this bug was happening I will confirm later tonight if this happens in multiplayer at all on the latest version.  I will close this out with a comment if that is the case as @daedalus4096 only tested in Singleplayer it seems

**Comment by daedalus4096** [comment]
Since I haven't heard from you further about this, I'm going to assume that this fix is holding.  If that's not the case, please file a new ticket.  Thanks for reporting the issue!
