### ISSUE TITLE
Cannot produce non-basic dusts in a Basic Calcinator that I can create in an Essence Furnace

### ISSUE THREAD

**Issue by Febilian** [daedalus4096/PrimalMagick#73]
Specifically, I am unable to create Blood Dust or Infernal Dust in the calcinator but I can in the furnace. Putting anything with the blood or infernal sources on it into the calcinator only gives me alchemical waste but produces the basic dusts just fine.

I'm assuming this is unintended behavior and I think it is likely that it also occurs with any other kinds of sources that you do not start the game with.

``Primal Magick 2.0.3``
``Forge 39.0.20``
``Minecraft 1.18.1``

**Comment by Febilian** [comment]
I think I may have solved my own problem - I hadn't actually broken and the re-placed the calcinator since discovering what the affinities were.

This was user error.

**Comment by daedalus4096** [comment]
While I'm glad you found a workaround, you shouldn't have had to do that.  Calcinators and the like should just work when you discover a new source.  I'm going to reopen this issue and track it down when I have an opportunity.

**Comment by daedalus4096** [comment]
In further testing, I found an issue that I believe would result in the behavior you describe.  It's now fixed in v2.0.4.  Should you encounter this issue again, please file a new ticket.  Thanks for reporting the problem and helping me make the mod better!
