### ISSUE TITLE
Spellcrafting altar text input takes precedence over JEI

### ISSUE THREAD

**Issue by Gronglegrowth** [daedalus4096/PrimalMagick#76]
If I try to search in JEI whilst in the spellcrafting altar's gui, it'll input the text into the spell naming section instead.

**Comment by Coderchris842** [comment]
that happens with pretty much everything, when I try to search jei in creative mode inventory the creative search takes precedence over JEI, it is a bug with jei.

**Comment by daedalus4096** [comment]
I'm not able to reproduce this issue with the Spellcrafting Altar in the upcoming 1.20.1 update for Primal Magick.  Presumably JEI has fixed this bug on their end.  Thank you for the report, and your patience!
