### ISSUE TITLE
[Mod compat] Enchanting table in-world not detected by the research table if Quark Oddities' matrix enchanter is enabled

### ISSUE THREAD

**Issue by Febilian** [daedalus4096/PrimalMagick#81]
With Quark Oddities Matrix Enchanting enabled, it's impossible to place down a vanilla enchanting table - placing the vanilla table down putsthe matrix enchanter in-world instead.

I think having the research table detect the matrix enchanter and act as though it's a vanilla enchanting table for "is this block placed near here?" purposes would be great as a QOL feature.

**Comment by daedalus4096** [comment]
That makes sense.  This should work as of the next version of the mod, planned as v2.0.5.  If it doesn't, please file a new ticket.  Thanks!
