### ISSUE TITLE
Some Bugs I found:

### ISSUE THREAD

**Issue by janperolino** [daedalus4096/PrimalMagick#82]
For some reason whenever a chunk with Primal Magick items such as calcinators, wand chargers, analyzing tables, is reloaded, all the items inside said blocks disappear. It happened a couple of times where I forgot that I left a wand inside a wand charger and went off to do some other things in faraway places and upon returning- said wand is nowhere to be found. This is also the same with the items inside calcinators, as well as analyzing tables. This problem makes it so that I have to stay in one place all the time just to make sure that I don't leave any items inside primal magick blocks before leaving. Although I have gotten used to it, it is still a very annoying and tedious process.

On a side note: The calcinator's configuration also resets whenever a chunk is loaded. So basically if I place a calcinator against a hallowed block so that it doesnt make alchemical waste out of hallowed affinity items. I have to replace it back again the next time the chunk is loaded. Otherwise it would start making alchemical waste as if I placed it with the wrong configuration. 

I am totally inexperienced with bug fixing and trouble shooting so please bear with me if i dont understand.

**Comment by daedalus4096** [comment]
Thank you for taking the time to report this issue.  It sounds like a bug that I recently fixed.  In v2.0.4, specifically.  What version are you playing with?

**Comment by janperolino** [comment]
Ahh I see, it might be because I haven't updated my list of mods. I realized I have been playing on the version 2.0.1. Alright then I will update the mods and see if the issue persists. Thank you so much!

**Comment by daedalus4096** [comment]
No problem!  I appreciate your taking the time to report the problem.  I'm going to close this issue in the meantime.  If you find that the problem persists, or that a new bug crops up, please open a new ticket.  Thanks again!
