### ISSUE TITLE
[Bug] Extreme lag when trying to view the affinites of a fluid cell from FTB:IC

### ISSUE THREAD

**Issue by Vapaman** [daedalus4096/PrimalMagick#98]
Mod version: 2.1.1
Forge version: 40.1.19
FTB IC version: ftb-industrial-contraptions-1802.1.4-build.139

When trying to view the affinities of a fluid cell from the FTB Industrial contraptions, there is a noticable drop in fps.

![2022-05-12_18 01 13](https://user-images.githubusercontent.com/77460466/168106331-d030bf3c-eac6-48af-b599-04f1c27ab0c0.png)
It is more extreme when there are more mods installed. I think it might have to do with the amount of fluids that are currently loaded.
![2022-05-12_18 03 17](https://user-images.githubusercontent.com/77460466/168106656-61985061-2906-4708-a92e-8610c05a2d83.png)

**Modlist for the second screenshot:**
AI-Improvements-1.18-0.4.0
alexsmobs-1.18.3
Amplified_Nether_v1.1.1
appleskin-forge-mc1.18-2.4.0
architectury-4.4.60
AutoRegLib-1.7-53
BiomesOPlenty-1.18.2-16.0.0.110-universal
citadel-1.11.3-1.18.2
Clumps-forge-1.18.2-8.0.0+8
configured-1.5.3-1.18.2
Controlling-forge-1.18.2-9.0+19
fabric-api-0.51.1+1.18.2
ferritecore-4.2.1-forge
ftb-chunks-forge-1802.3.6-build.145
ftb-industrial-contraptions-1802.1.4-build.139
ftb-library-forge-1802.3.6-build.115
ftb-teams-forge-1802.2.6-build.51
Jade-1.18.2-5.1.0
JadeAddons-1.18.2-2.0.0
jei-1.18.2-9.7.0.194
journeymap-1.18.2-5.8.3-forge
littlelogistics-mc1.18.2-v1.2.3
Mantle-1.18.2-1.9.20
MouseTweaks-forge-mc1.18-2.21
myrtrees-forge-1.1.0-build.29
Patchouli-1.18.2-67
Placebo-1.18.2-6.4.0
pneumaticcraft-repressurized-1.18.2-3.2.2-79
PrettyPipes-1.12.2
primalmagick-2.1.1
Quark-3.2-356
radium-0.7.10
radon-0.8.1
rubidium_extras-1.18.2_v1.3.1
rubidium-0.5.2a
selene-1.18.2-1.15.8
supplementaries-1.18.2-1.3.7
TConstruct-1.18.2-3.5.0.17
TerraBlender-forge-1.18.2-1.1.0.99
ToastControl-1.18.2-6.0.2

**Comment by daedalus4096** [comment]
This should be fixed in the upcoming 1.20.1 release.  Should you continue to encounter this sort of problem, please file a new ticket.  Thank you for your patience!
